# Generated by Django 5.2.1 on 2025-07-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApp', '0003_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(default='none', upload_to='documents/'),
        ),
    ]
