# Generated by Django 5.2.1 on 2025-07-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApp', '0005_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('Data Science', 'Data Science & AI Course'), ('Data Analytics', 'Data Analytics Course'), ('Microsoft', 'Microsoft Power BI Course'), ('python', 'Python Full Stack'), ('java', 'Java Full Stack'), ('PHP', 'PHP Full Stack')], default='python', max_length=50, null=True),
        ),
    ]
