# Generated by Django 5.2.1 on 2025-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonApp', '0006_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
